### PR TITLE
Chrome Application Setup

### PR DESCRIPTION
**Pull request by sunjay**
### This pull request represents our transition into the chrome environment

I've already merged master which means we get the new serial manager and serial port class. That means that serial should work out of the box even though `browser-serialport` doesn't support the parser argument.

Below you'll find all changes necessary to make our app a fully functional chrome app.
### Please code review & then merge

**Before merging, please test this on the real sculpture to make sure all code works exactly as it did before the chrome app. Checkout the README file for usage instructions.**

It may also be prudent to test this on the chromebox. We're still far away from deploying this for real on that system, but it may be worthwhile to see if it works or not so we know.

### CODE REVIEW

**Comment by kintel** [comment]
I've tested on Chrome, but not on Chrome box. With my recent commits, it looks like it works.
Note: When using it together with the text-emulator, we get an infinite loop - I assume that's a known issue.

Please take a quick look and merge at will.

**Comment by sunjay** [comment]
Awesome. I'll take a look at your commits. 

That's a known issue. We've got a task open to implement multiple users and I've written half of a design document for it. I believe I messaged you a little while ago as I was working on it. Haven't found a good approach yet. 

That's all separate from this though. I'll review your commits and let you know if I have any comment. 

Other than my review, is there anything left before we merge and close this?

**Comment by kintel** [comment]
No, it's good to go from my side.

**Comment by sunjay** [comment]
@kintel Please have a look at my commits. The serial all works now and the only thing left is being able to select your user in the sculpture client.

**Comment by sunjay** [comment]
✓ **Sunjay** - a new HELLO command sent from the embedded system as soon as it connects to any microcontroller will be added
✓ **Sunjay** - the number of HELLO attempts will be increased
✓ **Marius** - ~~no commands will be sent from microcontroller until hello has been received~~ The Arduino will ignore HELLO commands while it sending out its handshake messages and 100 ms afterwards
✓ **Sunjay & Marius** - RESET and INIT will be deprecated and removed
✓ **Sunjay** - Timeout safeguard will be added (it's now just to close ports that don't respond)
✓ **Sunjay** - Bad ports will be blacklisted
**Sunjay** - Issue with opening multiple serial ports in parallel - they appear to open in series
✓ **Sunjay** - Empty buildDisk() output
✓ **Sunjay** - Dealing with issues with `{ command: "PANEL-SET", data: {stripId: 0, panelId: 0, intensity: 0, color: "white"}}` to `PANEL-SET white` - ignoring any falsey arguments.

**Comment by sunjay** [comment]
Updated with completed items checked off

**Pull request merged**
